### ISSUE TITLE
[Feature]: Implement mod config

### ISSUE THREAD

**Issue by xPand4B** [WaldiNet/Towers_Of_The_Wild_Reworked#1]
Please implement a mod configuration.
This include...
*  a config file that can be read by the **client and server** 
* a integration for [ModMenu](https://www.curseforge.com/minecraft/mc-mods/modmenu).

**Comment by VoltHertz** [comment]
I know that for Xpand, but i just want a config file ATM... so i can make it more far from each other...

**Comment by xPand4B** [comment]
@VoltHertz Mod config has been implemented and will be released as v2.2.0, hope this can help you.
