### ISSUE TITLE
[Feature]: Fancy Waystones Plugin Support

### ISSUE THREAD

**Issue by rorysdonovan** [WaldiNet/Towers_Of_The_Wild_Reworked#18]
### Description

Hey! I saw the Fabric and Forge Waystones support for TOTWR, and was wondering if you could implement support for the Bukkit Plugin "[Fancy Waystones](https://www.spigotmc.org/resources/fancywaystones-waystones-and-waypoints-the-best-teleporter-and-location-marker-plugin.94376/)"

### Describe the solution you'd like

"Change the NBT file to have the correct waystones ok top and than refer to the modified one in the json world gen files"

- xPand 4/22/22 Discord

### Describe alternatives you've considered

I am not an expert in this area. Might be able to reach out to the FancyWaystones plugin developer for mutual support?

### Anything else?

Link: https://www.spigotmc.org/resources/fancywaystones-waystones-and-waypoints-the-best-teleporter-and-location-marker-plugin.94376/

**Comment by xPand4B** [comment]
Totally forgot to close this issue.
Just to recap, here's the discord chat regarding your mod-support request.

![image](https://user-images.githubusercontent.com/38140317/173184247-c402b882-850b-4913-bf55-65412d9e2627.png)

![unknown](https://user-images.githubusercontent.com/38140317/173184252-a0ae0f6b-e9a9-4cbd-9700-4a202c0860b4.png)
