### ISSUE TITLE
[Bug]: Fabric Waystones (Polymer Port) support broke on v4.0.0 (1.19) of the datapack

### ISSUE THREAD

**Issue by CamperSamu** [WaldiNet/Towers_Of_The_Wild_Reworked#25]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

With version 4.0.0 Fabric Waystones variant (Minecraft 1.19) of the datapack waystones won't spawn with the polymer port of the mod
![image](https://user-images.githubusercontent.com/32773961/174863157-f69386ab-47dc-4011-8f28-bcfdb81749ca.png)

### To Reproduce

1. Install TOTW-R and Fabric Waystones (Polymer Port)
2. Go to a tower

### Expected behavior

A waystone should spawn on the tower

### Mod Version

v4.0.0 (Fabric Waystones)

### Minecraft Version

1.19

### Java Version

Java 17

### Fabric Version (only if below v3.0.0)

- **Quilt:** ex. 0.17.1-1-19-0
- **QSL:** 2.0.0-beta.5
(Quilt is a popular Fabric fork, it supports Fabric API and Fabric functions)

**Comment by xPand4B** [comment]
Thanks for reporting this!

1. Did it work in 1.18.2 with "Fabric Waystones (Polymer Port)"?
2. Could you give me more info about the "Polymer Port"? I've never heard of this. The only version of Fabric Waystones I know is the [original](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)

**Comment by xPand4B** [comment]
@CamperSamu Fabric Waystones are now spawning again. Not sure why, but the waystone block entities were missing in the structure files, I re-added them.

Even if it's done now and the release v4.0.1 will be there soon it would be great if you could briefly explain what the "Polymer Port" is :)

**Comment by CamperSamu** [comment]
Thanks for the fix!
The "Polymer Port" is the serverside version of Fabric Waystones made by Patbox
https://modrinth.com/mod/polymer-ports-waystones
