### ISSUE TITLE
[Bug]: Towers of the same variant have the same Fabric Waystone name

### ISSUE THREAD

**Issue by Prymz** [WaldiNet/Towers_Of_The_Wild_Reworked#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Each tower variant has the same name for its Fabric Waystone:
**Derelict Towers** are always named: **Boyadawa**
**Grassy Derelict Towers** are always named: **Pozijuma**
**Regular Towers** are always named: **Cizumiqa**
**Jungle Towers** are always named: **Havirahi**
**Icy Towers** are always named: **Zazogura**
**Ocean Towers** are always named: **Yosugama**
**Warm Ocean Towers** are always named: **Buveciga**

### To Reproduce

Load world with Towers of the Wild: Reworked [Fabric Waystones] v4.0.1
`/locate` or `/place` 2 of any same tower structure variant

### Expected behavior

Fabric Waystone names should be randomized as they are generated in villages or when placed manually in the world.

### Mod Version

v4.0.1

### Mod Variation

Datapack - Fabric Waystones

### Minecraft Version

1.19

### Java Version

Java 17

### Fabric Version (only if below v3.0.0)

**Fabric Loader**: v0.14.8
**Fabric API**: v0.58.0+1.19

**Comment by xPand4B** [comment]
Many thanks for reporting this and also listing the names for each variant! ❤️ 
I just started looking why this is, but I'm not home till sunday.

Will keep you updated tho! 💪

**Comment by xPand4B** [comment]
And because you wrote at curseforge that it could be at your end, sadly, this isn't the case, just confirmed the issue :/
![image](https://user-images.githubusercontent.com/38140317/182935125-e063d200-237c-44c1-9712-43917d4758f6.png)

**Comment by xPand4B** [comment]
And also just found a floating shipwreck...so at least I'm not the only one introducing bugs xD
![image](https://user-images.githubusercontent.com/38140317/182935502-91e92d83-bce2-4781-9796-68ae22f70b32.png)

**Comment by Prymz** [comment]
Thanks for looking into it!  When I first noticed it, I was using additional datapacks including a world gen one, but did an isolated test before posting the issue to confirm it occurred in default vanilla generation.

**Comment by Prymz** [comment]
And about the floating shipwreck... I've noticed Minecraft doesn't seem to do a good job testing if structures fit into the terrain, like with villages decapitated by mountains or caves.

**Comment by xPand4B** [comment]
**Off-topic:**
With this attitude you would be a great QA tester in general

**Comment by Prymz** [comment]
Thanks!  If there is anything I can do, I'd like to get involved!

**Comment by Prymz** [comment]
I am very sorry if I am overstepping, but I wanted to try to make your job easier especially since you are not home.

I was curious how the Wraith's fabric waystones mod did their village structures for random waystone names so I opened the structure file in NBTExplorer how the waystone was encoded.
![image](https://user-images.githubusercontent.com/52138852/182959235-b6f88b93-d823-4c92-a987-81eabc86cfcd.png)
I then compared this to the regular fabric_waystone_tower_top structure file.
![image](https://user-images.githubusercontent.com/52138852/182959373-a7151312-b6b0-452e-b74d-fafb1954e21c.png)
The tower structures have more data stored their the waystone blocks.  I deleted the tags not present in the village waystone structure and that seemed to fix it; the waystone names were random for all the structures that I changed.

**Comment by xPand4B** [comment]
Great job! Many thanks! ♥️That's the issue.

I remember something similar happened to the other waystones mod that is supported.

The whole topic is kinda tricky, because the stuff you just removed is auto generated if you're editing the structure inside Minecraft...

Sorry for the inconveniences, I'll commit and release the fix once I'm back home.

**Comment by Prymz** [comment]
No inconveniences!  Thank you for being so responsive and receptive!

**Comment by xPand4B** [comment]
@Prymz I just updated everything and created the .zip archive. Would be great if you would do a small check on your side if everything's working as expected.

[Towers_Of_The_Wild_Reworked_v4.0.2_Fabric_Waystones.zip](https://github.com/WaldiNet/Towers_Of_The_Wild_Reworked/files/9277050/Towers_Of_The_Wild_Reworked_v4.0.2_Fabric_Waystones.zip)

**Comment by Prymz** [comment]
It looks good.  I did not encounter any repeated names.  Thank you!

**Comment by xPand4B** [comment]
@Prymz The fix has been released on this Repo and Curseforge as well _(Curse might take a bit to appear because they have am approval process after uploading a new version)_.

Again, many thanks for your contribution! 🚀
