### ISSUE TITLE
Waystones not generating

### ISSUE THREAD

**Issue by ShinyRobotGod** [WaldiNet/Towers_Of_The_Wild_Reworked#30]
Hello.  I am using 4.0.2 of the datapack with Fabric Waystones 3.0.5+mc1.19.2.  No waystones generate at the towers.

**Comment by xPand4B** [comment]
May Sound weird, but is your chest on top generating in the middle or at the edge?

**Comment by ShinyRobotGod** [comment]
The chests at the top are generating at the edge.

**Comment by xPand4B** [comment]
Could you please check if that's the exact version you downloaded?

https://www.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack/files/3923465

v4.0.2 [Waystones] is for the forge version of the Waystones mod, you would need [Fabric Waystones].

**Comment by ShinyRobotGod** [comment]
This is the waystones mod: wraith-waystones-3.0.5+mc1.19.2.  It's from the Fabric Waystones files.  Latest one as of yesterday.  The waystones are generating in villages as they should.  

This is the datapack name:  Towers_Of_The_Wild_Reworked_v4.0.2_Waystones.

**Comment by xPand4B** [comment]
Yeah, you're using the wrong Tote version, it has to be "Fabric Waystones" instead of just "Waystones"

Please try I file I send previously

**Comment by ShinyRobotGod** [comment]
Yes, sorry.  I realize now I was using the wrong file.  Thanks for helping me. I appreciate it.
