### ISSUE TITLE
[Bug]: [1.20.1] Missing Towertop?

### ISSUE THREAD

**Issue by pewblaze** [WaldiNet/Towers_Of_The_Wild_Reworked#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Im using the 1.20.1 Version for Fabric Waystones, the towertop is missing on the regular ones:
![2023-08-26_15 29 34](https://github.com/WaldiNet/Towers_Of_The_Wild_Reworked/assets/96242065/cc8dc098-ac05-4b3d-ada5-bf60ef799f61)

### To Reproduce

Download the 1.20.1 Version (Towers_Of_The_Wild_Reworked_v4.2.0_Fabric_Waystones.zip), create world & search for a regular tower

### Expected behavior

There should be a top i guess ^^

### Mod Version

v4.2.0

### Mod Variation

Datapack - Fabric Waystones

### Minecraft Version

1.20.1

### Java Version

Java 20

### Fabric Version (only if below v3.0.0)

- **Fabric:** ex. 0.12.5-1-17-1
- **Fabric API:** ex. 0.42.1+1.17

**Comment by xPand4B** [comment]
Thanks, you're right!

I had a wrong naming for the regular tower top. Fix will be released in a few minutes

**Comment by xPand4B** [comment]
@pewblaze Your issue has been fixed and released _(is still in review for a few minutes)_
Thanks for contributing!

**GitHub:** https://github.com/WaldiNet/Towers_Of_The_Wild_Reworked/releases/tag/v4.2.1
**Curseforge:** https://www.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack/files?version=1.20.1
**Modrinth:** https://modrinth.com/datapack/towers-of-the-wild-reworked/versions?g=1.20.1
