### ISSUE TITLE
[Bug]: Incompatibility with Repurposed Structures

### ISSUE THREAD

**Issue by griffin4cats** [WaldiNet/Towers_Of_The_Wild_Reworked#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Installation alongside Repurposed structures causes an error with /locate

### To Reproduce

Install Repurposed Structures

### Expected behavior

/locate should (eventually) return a teleport command to the nearest structure of any given type in Towers of the Wild

### Mod Version

2.0.0

### Minecraft Version

1.18

### Java Version

Java 17

### Fabric Version

0.12.11-1-18
0.44.0+1.18

### Anything else?

![image](https://user-images.githubusercontent.com/62814690/145773529-f29f3275-2a49-4ce4-8c29-f8e99ff1c728.png)
An image of what occurs

**Comment by xPand4B** [comment]
Just to clarify because the options for 1.18 and 1.18.1 were added afterwards:
Which version are you using? 1.18 or 1.18.1?

**Comment by griffin4cats** [comment]
My bad, 1.18 not 1.18.1

**Comment by xPand4B** [comment]
TotW isn't officially compatible with 1.18. Because recently there was a severe Java security issue which was kinda fixed in 1.18.1 we skipped one version entirely.

Perhaps try this again for 1.18.1, think this should do the trick with Towers ans RS.

**Comment by michinoke** [comment]
I'm also having issues with locate being unable to find towers when repurposed structures is installed. Searching for every type of tower just responds 'Could not find that structure nearby' regardless of distance travelled. Disable RS and locate works. Nothing obvious in log output.

Minecraft 1.18.1
Fabric Loader 0.12.12 (tested with 0.13.0 as well)
Balm (Fabric Edition) 2.4.1+0
Cloth Config API 6.1.50 (tested with 6.1.48 as well)
Fabric API 0.46.4+1.18
Feature NBT Deadlock Be Gone 1.0.1+1.18.1
No Null Processors 2.0.1+1.18.1
Repurposed Structures (Fabric) 3.3.6+1.18.1
Towers of the Wild: Reworked (Fabric) 2.1.1

**Comment by xPand4B** [comment]
Hmm, weird. I'll try to check the compatibility this weekend.

@griffin4cats  @michinoke  Out of curiosity, could you try this again but instead of the Towers mod with another one that adds structures?

**Comment by michinoke** [comment]
I tried with the latest Mo' Structures and the same problem occurs when RS is enabled. Locating vanilla structures works, locating RS structures work but locating anything from Mo doesn't. Disable RS and I can locate from Mo.

**Comment by xPand4B** [comment]
If that's the case I'm quite sure this issue has to do with the RS mod. If it's the same behavior even with Mos instead of the towers 🤔 As stated, I'll have a look at it this weekend, but after hearing this I'm not sure if I can do more than creating an issue for RS as well :/

Maybe I can find the issue and propose a PR there, but that's not guaranteed.

**Comment by michinoke** [comment]
I've opened an issue in Repurposed, locate wasn't actually the problem. Repurposed is somehow blocking the generation of structures for your mod.

**Comment by xPand4B** [comment]
I really appreciate your effort @michinoke !

**Comment by michinoke** [comment]
This is fixed as of Repurposed Structures 3.3.7 (requires latest Fabric API).
